#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
# entry("read");
# entry("write");
# entry("close");
entry("kill");
entry("exec");
# entry("open");
# entry("mknod");
entry("unlink");
# entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
# entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");

entry("send"); # [New] syscall stub for send
entry("recv"); # [New] syscall stub for recv

entry("getppid"); # [New] syscall stub for get parent pid

entry("register_service"); # [New] syscall stub for registering server process
entry("lookup_service"); # [New] syscall stub for looking up PID of a server process

entry("disk_read");     # [New] syscall stub for disk read
entry("disk_write");    # [New] syscall stub for disk write

entry("debug");

entry("console_read");
entry("console_write");
